# Generated by Django 4.1.4 on 2022-12-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Foto', models.ImageField(upload_to='media/images')),
                ('Url', models.URLField(blank=True)),
                ('Tags', models.TextField()),
            ],
        ),
    ]
