# Generated by Django 4.1.4 on 2022-12-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Foto',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Titulo',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Url',
            new_name='url',
        ),
    ]
