# Generated by Django 4.1.4 on 2022-12-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_rename_descripcion_project_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='foto',
            field=models.CharField(max_length=500),
        ),
    ]
