# Generated by Django 4.1.4 on 2022-12-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_project_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(verbose_name='Fecha de petición')),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Direccion IP',
                'verbose_name_plural': 'Direcciones de Ip',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='foto',
            field=models.CharField(max_length=500, verbose_name='url de la imagen'),
        ),
    ]
