# Generated by Django 4.1.4 on 2022-12-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_ipaddress_alter_project_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='foto',
            field=models.URLField(max_length=500),
        ),
    ]
