# Generated by Django 4.1.4 on 2022-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_alter_project_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
    ]
